version: "3"
services:
  database:
    container_name: ppclothesDataBase
    build: .
    image: database
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: flukefriendbest
      MYSQL_DATABASE: project
    volumes: 
      - "./script/ppclothesDB.sql:/docker-entrypoint-initdb.d/ppclothesDB.sql"
      - "./script/grantUsers.sql:/docker-entrypoint-initdb.d/grantUsers.sql"
    ports:
      - "3306:3306"

networks:
  default:
    external:
      name: NETWORK
